export const FAKE_POPULARS = [
  {
    backdrop_path: "/5vUux2vNUTqwCzb7tVcH18XnsF.jpg",
    first_air_date: "2022-09-21",
    genre_ids: [18, 80],
    id: 113988,
    name: "Dahmer – Monster: The Jeffrey Dahmer Story",
    origin_country: ["US"],
    original_language: "en",
    original_name: "Dahmer – Monster: The Jeffrey Dahmer Story",
    overview:
      "Across more than a decade, 17 teen boys and young men were murdered by convicted killer Jeffrey Dahmer. How did he evade arrest for so long?",
    popularity: 6817.15,
    poster_path: "/f2PVrphK0u81ES256lw3oAZuF3x.jpg",
    vote_average: 8.4,
    vote_count: 591,
  },
];

export const FAKE_RECOMMENDATION_DATA = [
  {
    adult: false,
    backdrop_path: "/iHSwvRVsRyxpX7FE7GbviaDvgGZ.jpg",
    id: 119051,
    name: "Wednesday",
    original_language: "en",
    original_name: "Wednesday",
    overview:
      "Wednesday Addams is sent to Nevermore Academy, a bizarre boarding school where she attempts to master her psychic powers, stop a monstrous killing spree of the town citizens, and solve the supernatural mystery that affected her family 25 years ago — all while navigating her new relationships.",
    poster_path: "/9PFonBhy4cQy7Jz20NpMygczOkv.jpg",
    media_type: "tv",
    genre_ids: [10765, 9648, 35],
    popularity: 225.639,
    first_air_date: "2022-11-23",
    vote_average: 8.578,
    vote_count: 7212,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/etj8E2o0Bud0HkONVQPjyCkIvpv.jpg",
    id: 94997,
    name: "House of the Dragon",
    original_language: "en",
    original_name: "House of the Dragon",
    overview:
      "The Targaryen dynasty is at the absolute apex of its power, with more than 15 dragons under their yoke. Most empires crumble from such heights. In the case of the Targaryens, their slow fall begins when King Viserys breaks with a century of tradition by naming his daughter Rhaenyra heir to the Iron Throne. But when Viserys later fathers a son, the court is shocked when Rhaenyra retains her status as his heir, and seeds of division sow friction across the realm.",
    poster_path: "/1X4h40fcB4WWUmIBK0auT4zRBAV.jpg",
    media_type: "tv",
    genre_ids: [10765, 18, 10759],
    popularity: 171.754,
    first_air_date: "2022-08-21",
    vote_average: 8.465,
    vote_count: 3240,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/42iDbOtqWqPvI3FnP3KafLFrQq.jpg",
    id: 209167,
    name: "Conversations with a Killer: The Jeffrey Dahmer Tapes",
    original_language: "en",
    original_name: "Conversations with a Killer: The Jeffrey Dahmer Tapes",
    overview:
      "Serial killer Jeffrey Dahmer confesses to his gruesome crimes in unguarded interviews, offering an unsettling view into a disturbed mind.",
    poster_path: "/5BTn4GxWL48BP8OkfiatxZ6qpuE.jpg",
    media_type: "tv",
    genre_ids: [99, 80],
    popularity: 18.237,
    first_air_date: "2022-10-07",
    vote_average: 7.972,
    vote_count: 181,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/1rO4xoCo4Z5WubK0OwdVll3DPYo.jpg",
    id: 84773,
    name: "The Lord of the Rings: The Rings of Power",
    original_language: "en",
    original_name: "The Lord of the Rings: The Rings of Power",
    overview:
      "Beginning in a time of relative peace, we follow an ensemble cast of characters as they confront the re-emergence of evil to Middle-earth. From the darkest depths of the Misty Mountains, to the majestic forests of Lindon, to the breathtaking island kingdom of Númenor, to the furthest reaches of the map, these kingdoms and characters will carve out legacies that live on long after they are gone.",
    poster_path: "/mYLOqiStMxDK3fYZFirgrMt8z5d.jpg",
    media_type: "tv",
    genre_ids: [10759, 10765, 18],
    popularity: 154.188,
    first_air_date: "2022-09-01",
    vote_average: 7.439,
    vote_count: 2083,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/bebZzFw1mBzF9UwCO3ocW0PIIby.jpg",
    id: 210232,
    name: "The Watcher",
    original_language: "en",
    original_name: "The Watcher",
    overview:
      "A family moves into their suburban dream home, only to discover they've inherited a nightmare.",
    poster_path: "/6RrseODZo2e66XOzC1XMzMuecnf.jpg",
    media_type: "tv",
    genre_ids: [18, 9648],
    popularity: 28.409,
    first_air_date: "2022-10-13",
    vote_average: 7.4,
    vote_count: 422,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/uJ16DD1dj4CQLPNCWIoiOF3l8np.jpg",
    id: 100088,
    name: "The Last of Us",
    original_language: "en",
    original_name: "The Last of Us",
    overview:
      "Twenty years after modern civilization has been destroyed, Joel, a hardened survivor, is hired to smuggle Ellie, a 14-year-old girl, out of an oppressive quarantine zone. What starts as a small job soon becomes a brutal, heartbreaking journey, as they both must traverse the United States and depend on each other for survival.",
    poster_path: "/uKvVjHNqB5VmOrdxqAt2F7J78ED.jpg",
    media_type: "tv",
    genre_ids: [18],
    popularity: 267.264,
    first_air_date: "2023-01-15",
    vote_average: 8.705,
    vote_count: 3664,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/s1xnjbOIQtwGObPnydTebp74G2c.jpg",
    id: 90669,
    name: "1899",
    original_language: "de",
    original_name: "1899",
    overview:
      "Passengers on an immigrant ship traveling to the new continent get caught in a mysterious riddle when they find a second vessel adrift on the open sea.",
    poster_path: "/gZleGu1MQVBArH2dlpZ9CGi0hhy.jpg",
    media_type: "tv",
    genre_ids: [9648, 18],
    popularity: 53.792,
    first_air_date: "2022-11-17",
    vote_average: 7.65,
    vote_count: 942,
    origin_country: ["DE"],
  },
  {
    adult: false,
    backdrop_path: "/56v2KjBlU4XaOv9rVYEQypROD7P.jpg",
    id: 66732,
    name: "Stranger Things",
    original_language: "en",
    original_name: "Stranger Things",
    overview:
      "When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces, and one strange little girl.",
    poster_path: "/49WJfeN0moxb9IPfGn8AIqMGskD.jpg",
    media_type: "tv",
    genre_ids: [18, 10765, 9648],
    popularity: 272.113,
    first_air_date: "2016-07-15",
    vote_average: 8.629,
    vote_count: 15715,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/6LWy0jvMpmjoS9fojNgHIKoWL05.jpg",
    id: 1399,
    name: "Game of Thrones",
    original_language: "en",
    original_name: "Game of Thrones",
    overview:
      "Seven noble families fight for control of the mythical land of Westeros. Friction between the houses leads to full-scale war. All while a very ancient evil awakens in the farthest north. Amidst the war, a neglected military order of misfits, the Night's Watch, is all that stands between the realms of men and icy horrors beyond.",
    poster_path: "/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg",
    media_type: "tv",
    genre_ids: [10765, 18, 10759],
    popularity: 389.867,
    first_air_date: "2011-04-17",
    vote_average: 8.4,
    vote_count: 21322,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/3tEuJWbFjyQL2m4AlGVB1cRqn1E.jpg",
    id: 83659,
    name: "Guillermo del Toro's Cabinet of Curiosities",
    original_language: "en",
    original_name: "Guillermo del Toro's Cabinet of Curiosities",
    overview:
      "Bizarre nightmares unfold in eight tales of terror in this visually stunning, spine-tingling horror collection curated by Guillermo del Toro.",
    poster_path: "/a91e9hpWwfCqxJI4xM9Q2RhuxgI.jpg",
    media_type: "tv",
    genre_ids: [18, 9648],
    popularity: 60.527,
    first_air_date: "2022-10-25",
    vote_average: 7.717,
    vote_count: 559,
    origin_country: ["US"],
  },
];
